import { Montserrat, Poppins } from 'next/font/google';
import "./globals.css";

const poppins = Poppins({
  weight: ['400', '600'],
  subsets: ['latin'],
});

const montserrat = Montserrat({
  weight: ['400', '600'],
  subsets: ['latin'],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${montserrat.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
