import { Montserrat, Poppins } from 'next/font/google';
import "./globals.css";
import Footer from './components/Footer';
import Header from './components/Header';

const poppins = Poppins({
  weight: ['400', '600'],
  subsets: ['latin'],
});

const montserrat = Montserrat({
  weight: ['400', '600'],
  subsets: ['latin'],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${montserrat.variable}`}
      >
        <div className="w-full px-4 md:px-20">
          <Header />
        </div>
        {children}
        <Footer />
      </body>
    </html>
  );
}
